name: Deploy to Production

on:
  workflow_run:
    workflows: [ "Publish Package to GHCR" ]
    types: [ completed ]
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Full Stack
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    uses: SmartPotTech/.github/.github/workflows/deploy.yml@main
    secrets: inherit
